@startuml
Программирование ---> Императивное
Программирование ---> Декларативное
Императивное --> Структурное
Императивное --> Неструктурное
Структурное --> Процедурное
Структурное --> Объектно_ориентированное
Объектно_ориентированное --> Прототипное
Объектно_ориентированное --> На_основе_классов
Декларативное --> Функциональное
Декларативное --> Логическое
Функциональное --> Аппликатное
Функциональное --> Комбинаторное
Структурное ..> Функциональное
@enduml